<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.Wpf" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="K:\User_Files\Dev\mochineko\CSharp_Project\VorticeDirectX_Sample\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="K:\User_Files\Dev\mochineko\CSharp_Project\VorticeDirectX_Sample\.editorconfig" />
  </ItemGroup>

<ItemGroup>
	<None Update="Assets\TestShader.hlsl">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
</ItemGroup>	

</Project>
